-- Converts every table's bigint identity id (and the FK columns pointing at them) to UUIDv7,
-- generated with Postgres 18's built-in uuidv7(), and adds an autogenerated unique slug to
-- assignments. Existing rows are backfilled and relationships preserved throughout.

-- 1. Add UUID columns and backfill them from the existing bigint ids, parent-first so children
--    can look up the parent's freshly generated UUID.

ALTER TABLE users ADD COLUMN uuid_id uuid NOT NULL DEFAULT uuidv7();

ALTER TABLE assignments ADD COLUMN uuid_id uuid NOT NULL DEFAULT uuidv7();
ALTER TABLE assignments ADD COLUMN uuid_created_by uuid;
UPDATE assignments a SET uuid_created_by = u.uuid_id FROM users u WHERE u.id = a.created_by;
ALTER TABLE assignments ALTER COLUMN uuid_created_by SET NOT NULL;

ALTER TABLE assignments ADD COLUMN slug varchar(220);
WITH base AS (
  SELECT id, regexp_replace(regexp_replace(lower(title), '[^a-z0-9]+', '-', 'g'), '^-+|-+$', '', 'g') AS s
  FROM assignments
), numbered AS (
  SELECT id, s, row_number() OVER (PARTITION BY s ORDER BY id) AS rn
  FROM base
)
UPDATE assignments a
SET slug = CASE
  WHEN numbered.rn = 1 THEN COALESCE(NULLIF(numbered.s, ''), 'assignment')
  ELSE COALESCE(NULLIF(numbered.s, ''), 'assignment') || '-' || numbered.rn
END
FROM numbered
WHERE numbered.id = a.id;
ALTER TABLE assignments ALTER COLUMN slug SET NOT NULL;
ALTER TABLE assignments ADD CONSTRAINT assignments_slug_key UNIQUE (slug);

ALTER TABLE projects ADD COLUMN uuid_id uuid NOT NULL DEFAULT uuidv7();
ALTER TABLE projects ADD COLUMN uuid_assignment_id uuid;
ALTER TABLE projects ADD COLUMN uuid_submitter_id uuid;
UPDATE projects p SET uuid_assignment_id = a.uuid_id FROM assignments a WHERE a.id = p.assignment_id;
UPDATE projects p SET uuid_submitter_id = u.uuid_id FROM users u WHERE u.id = p.submitter_id;
ALTER TABLE projects ALTER COLUMN uuid_assignment_id SET NOT NULL;
ALTER TABLE projects ALTER COLUMN uuid_submitter_id SET NOT NULL;

ALTER TABLE tech_labels ADD COLUMN uuid_id uuid NOT NULL DEFAULT uuidv7();
ALTER TABLE tech_labels ADD COLUMN uuid_created_by uuid;
UPDATE tech_labels t SET uuid_created_by = u.uuid_id FROM users u WHERE u.id = t.created_by;
ALTER TABLE tech_labels ALTER COLUMN uuid_created_by SET NOT NULL;

ALTER TABLE project_tech_labels ADD COLUMN uuid_project_id uuid;
ALTER TABLE project_tech_labels ADD COLUMN uuid_tech_label_id uuid;
UPDATE project_tech_labels ptl SET uuid_project_id = p.uuid_id FROM projects p WHERE p.id = ptl.project_id;
UPDATE project_tech_labels ptl SET uuid_tech_label_id = t.uuid_id FROM tech_labels t WHERE t.id = ptl.tech_label_id;
ALTER TABLE project_tech_labels ALTER COLUMN uuid_project_id SET NOT NULL;
ALTER TABLE project_tech_labels ALTER COLUMN uuid_tech_label_id SET NOT NULL;

ALTER TABLE votes ADD COLUMN uuid_id uuid NOT NULL DEFAULT uuidv7();
ALTER TABLE votes ADD COLUMN uuid_project_id uuid;
ALTER TABLE votes ADD COLUMN uuid_voter_id uuid;
UPDATE votes v SET uuid_project_id = p.uuid_id FROM projects p WHERE p.id = v.project_id;
UPDATE votes v SET uuid_voter_id = u.uuid_id FROM users u WHERE u.id = v.voter_id;
ALTER TABLE votes ALTER COLUMN uuid_project_id SET NOT NULL;
ALTER TABLE votes ALTER COLUMN uuid_voter_id SET NOT NULL;

-- 2. Drop constraints, indexes and columns built on the old bigint ids.

ALTER TABLE votes DROP CONSTRAINT votes_project_voter_key;
ALTER TABLE votes DROP CONSTRAINT votes_project_id_fkey;
ALTER TABLE votes DROP CONSTRAINT votes_voter_id_fkey;
DROP INDEX votes_project_id_idx;

ALTER TABLE project_tech_labels DROP CONSTRAINT project_tech_labels_pkey;
ALTER TABLE project_tech_labels DROP CONSTRAINT project_tech_labels_project_id_fkey;
ALTER TABLE project_tech_labels DROP CONSTRAINT project_tech_labels_tech_label_id_fkey;

ALTER TABLE projects DROP CONSTRAINT projects_assignment_id_fkey;
ALTER TABLE projects DROP CONSTRAINT projects_submitter_id_fkey;
DROP INDEX projects_assignment_id_idx;
DROP INDEX projects_submitter_id_idx;

ALTER TABLE tech_labels DROP CONSTRAINT tech_labels_created_by_fkey;
ALTER TABLE assignments DROP CONSTRAINT assignments_created_by_fkey;

ALTER TABLE votes DROP CONSTRAINT votes_pkey;
ALTER TABLE projects DROP CONSTRAINT projects_pkey;
ALTER TABLE tech_labels DROP CONSTRAINT tech_labels_pkey;
ALTER TABLE assignments DROP CONSTRAINT assignments_pkey;
ALTER TABLE users DROP CONSTRAINT users_pkey;

ALTER TABLE votes DROP COLUMN id, DROP COLUMN project_id, DROP COLUMN voter_id;
ALTER TABLE project_tech_labels DROP COLUMN project_id, DROP COLUMN tech_label_id;
ALTER TABLE projects DROP COLUMN id, DROP COLUMN assignment_id, DROP COLUMN submitter_id;
ALTER TABLE tech_labels DROP COLUMN id, DROP COLUMN created_by;
ALTER TABLE assignments DROP COLUMN id, DROP COLUMN created_by;
ALTER TABLE users DROP COLUMN id;

-- 3. Rename the UUID columns into place.

ALTER TABLE users RENAME COLUMN uuid_id TO id;

ALTER TABLE assignments RENAME COLUMN uuid_id TO id;
ALTER TABLE assignments RENAME COLUMN uuid_created_by TO created_by;

ALTER TABLE projects RENAME COLUMN uuid_id TO id;
ALTER TABLE projects RENAME COLUMN uuid_assignment_id TO assignment_id;
ALTER TABLE projects RENAME COLUMN uuid_submitter_id TO submitter_id;

ALTER TABLE tech_labels RENAME COLUMN uuid_id TO id;
ALTER TABLE tech_labels RENAME COLUMN uuid_created_by TO created_by;

ALTER TABLE project_tech_labels RENAME COLUMN uuid_project_id TO project_id;
ALTER TABLE project_tech_labels RENAME COLUMN uuid_tech_label_id TO tech_label_id;

ALTER TABLE votes RENAME COLUMN uuid_id TO id;
ALTER TABLE votes RENAME COLUMN uuid_project_id TO project_id;
ALTER TABLE votes RENAME COLUMN uuid_voter_id TO voter_id;

-- 4. Re-add primary keys, foreign keys, unique constraints and indexes.

ALTER TABLE users ADD PRIMARY KEY (id);
ALTER TABLE assignments ADD PRIMARY KEY (id);
ALTER TABLE projects ADD PRIMARY KEY (id);
ALTER TABLE tech_labels ADD PRIMARY KEY (id);
ALTER TABLE votes ADD PRIMARY KEY (id);
ALTER TABLE project_tech_labels ADD PRIMARY KEY (project_id, tech_label_id);

ALTER TABLE assignments ADD CONSTRAINT assignments_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE tech_labels ADD CONSTRAINT tech_labels_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE projects ADD CONSTRAINT projects_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES assignments (id) ON DELETE CASCADE;
ALTER TABLE projects ADD CONSTRAINT projects_submitter_id_fkey FOREIGN KEY (submitter_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE project_tech_labels ADD CONSTRAINT project_tech_labels_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE project_tech_labels ADD CONSTRAINT project_tech_labels_tech_label_id_fkey FOREIGN KEY (tech_label_id) REFERENCES tech_labels (id) ON DELETE CASCADE;
ALTER TABLE votes ADD CONSTRAINT votes_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE votes ADD CONSTRAINT votes_voter_id_fkey FOREIGN KEY (voter_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE votes ADD CONSTRAINT votes_project_voter_key UNIQUE (project_id, voter_id);

CREATE INDEX projects_assignment_id_idx ON projects (assignment_id);
CREATE INDEX projects_submitter_id_idx ON projects (submitter_id);
CREATE INDEX votes_project_id_idx ON votes (project_id);

-- 5. From now on ids are generated by Hibernate (UuidGenerator, VERSION_7) before insert, the
--    same way created_at is set in the entity constructor rather than left to a column default
--    — drop the migration-time defaults so that stays the single source of truth.

ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
ALTER TABLE assignments ALTER COLUMN id DROP DEFAULT;
ALTER TABLE projects ALTER COLUMN id DROP DEFAULT;
ALTER TABLE tech_labels ALTER COLUMN id DROP DEFAULT;
ALTER TABLE votes ALTER COLUMN id DROP DEFAULT;
